framework:
    messenger:
        failure_transport: failed

        transports:
            # Default async transport via Redis (see .env MESSENGER_TRANSPORT_DSN)
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            # Keep a separate failure transport in DB (optional)
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            'App\Message\MqttMessage': async
            'App\Message\TagReadingsBatchMessage': async
