#!/usr/bin/env sh
set -eu

# Defaults
: "${MQTT_PORT:=1883}"
: "${MQTT_USERNAME:=}"
: "${MQTT_PASSWORD:=}"

CONFIG_DIR=/mosquitto/config
DATA_DIR=/mosquitto/data
LOG_DIR=/mosquitto/log

mkdir -p "$CONFIG_DIR" "$DATA_DIR" "$LOG_DIR"

CONF_FILE="$CONFIG_DIR/mosquitto.conf"
PASS_FILE="$CONFIG_DIR/passwordfile"

# Build mosquitto.conf from env
{
  echo "# Auto-generated by entrypoint"
  echo "listener ${MQTT_PORT} 0.0.0.0"
  if [ -n "${MQTT_USERNAME}" ] && [ -n "${MQTT_PASSWORD}" ]; then
    echo "allow_anonymous false"
    echo "password_file ${PASS_FILE}"
  else
    # If no credentials provided, allow anonymous for local dev
    echo "allow_anonymous true"
  fi
  echo "persistence true"
  echo "persistence_location ${DATA_DIR}/"
  echo "log_dest stdout"
} > "$CONF_FILE"

# Create password file if credentials provided
if [ -n "${MQTT_USERNAME}" ] && [ -n "${MQTT_PASSWORD}" ]; then
  mosquitto_passwd -b -c "$PASS_FILE" "$MQTT_USERNAME" "$MQTT_PASSWORD" >/dev/null 2>&1 || true
fi

exec mosquitto -c "$CONF_FILE"

